dict_country = {
                'ANTIGUA AND BARBUDA': 'ANTIGUA & BARBUDA',
                'BAHAMAS, THE': 'BAHAMAS',
                'BOSNIA AND HERZEGOVINA': 'BOSNIA & HERZEGOVINA',
                'BRUNEI DARUSSALAM': 'BRUNEI (DARUSSALAM)',
                'CABO VERDE': 'CAPE VERDE',
                'CHINA (MAINLAND)': 'CHINA',
                'CZECH REPUBLIC': 'CZECHIA',
                'CONGO, DEM. REP.': 'DRC',
                'DEMOCRATIC REPUBLIC OF THE CONGO (FORMERLY ZAIRE)': 'DRC',
                'CONGO, REP.': 'CONGO',
                'COTE D IVOIRE': "COTE D'IVOIRE",
                'EGYPT, ARAB REP.': 'EGYPT',
                'FEDERATED STATES OF MICRONESIA': 'MICRONESIA',
                'MICRONESIA, FED. STS.': 'MICRONESIA',
                'FRANCE (INCLUDING MONACO)': 'FRANCE',
                'GAMBIA, THE': 'GAMBIA',
                'GUINEA-BISSAU': 'GUINEA BISSAU',
                'HONG KONG SPECIAL ADMINSTRATIVE REGION OF CHINA': 'HONG KONG',
                'HONG KONG SAR, CHINA': 'HONG KONG',
                'IRAN, ISLAMIC REP.': 'IRAN',
                'ISLAMIC REPUBLIC OF IRAN': 'IRAN',
                'ITALY (INCLUDING SAN MARINO)': 'ITALY',
                'KYRGYZ REPUBLIC': 'KYRGYZSTAN',
                'LAO PDR': 'LAOS',
                'LAO PEOPLE S DEMOCRATIC REPUBLIC': 'LAOS',
                'MACAO SAR': 'MACAO',
                'MACAU SPECIAL ADMINISTRATIVE REGION OF CHINA': 'MACAO',
                'LIBYAN ARAB JAMAHIRIYAH': 'LIBYA',
                'MACEDONIA': 'NORTH MACEDONIA',
                'MYANMAR (FORMERLY BURMA)': 'MYANMAR',
                'PLURINATIONAL STATE OF BOLIVIA': 'BOLIVIA',
                'REPUBLIC OF CAMEROON': 'CAMEROON',
                'REPUBLIC OF MOLDOVA': 'MOLDOVA',
                'REPUBLIC OF KOREA': 'SOUTH KOREA',
                'KOREA, REP.': 'SOUTH KOREA',
                "KOREA, DEM. PEOPLE'S REP.": 'NORTH KOREA',
                'DEMOCRATIC PEOPLE S REPUBLIC OF KOREA': 'NORTH KOREA',
                'REPUBLIC OF SOUTH SUDAN': 'SOUTH SUDAN',
                'REPUBLIC OF SUDAN': 'SUDAN',
                'ST. LUCIA': 'SAINT LUCIA',
                'SAINT MARTIN (DUTCH PORTION)': 'SINT MAARTEN (DUTCH PART)',
                'SAO TOME AND PRINCIPE': 'SAO TOME & PRINCIPE',
                'SLOVAK REPUBLIC': 'SLOVAKIA',
                'ST. KITTS AND NEVIS': 'ST. KITTS-NEVIS',
                'ST. VINCENT AND THE GRENADINES': 'ST. VINCENT & THE GRENADINES',
                'SWAZILAND': 'ESWATINI',
                'TIMOR-LESTE (FORMERLY EAST TIMOR)': 'TIMOR-LESTE',
                'TURKEY': 'TURKIYE',
                'UNITED REPUBLIC OF TANZANIA': 'TANZANIA',
                'UNITED STATES OF AMERICA': 'USA',
                'UNITED STATES': 'USA',
                'VENEZUELA, RB': 'VENEZUELA',
                'VIETNAM': 'VIET NAM',
                'YEMEN, REP.': 'YEMEN',
                'FAEROE ISLANDS': 'FAROE ISLANDS',
                'YUGOSLAVIA (FORMER SOCIALIST FEDERAL REPUBLIC)': 'YUGOSLAVIA',
                'YUGOSLAVIA (MONTENEGRO & SERBIA)': 'YUGOSLAVIA'
                }
def get_dict():
    return dict_country
